### ISSUE TITLE
Android: FeedbackManager is always registered

### ISSUE THREAD

**Issue by piotrowski** [lostintangent/cordova-plugin-hockeyapp#17]
By using .start() on Android currently you always start the FeedbackManager: https://github.com/peutetre/cordova-plugin-hockeyapp/blob/master/src/android/HockeyApp.java#L28
This may not be correct and the best way to handle things. This could either be an option or a seperate call to make, so the user can decide if he wants this module of HockeyApp activated or not.

**Comment by mikeljames** [comment]
Does this actually open the feedback manager? Or does it just have it sat ready waiting in memory? I only ask as i'm about to integrate with this library, I've used it before on iOS but this wasn't the behaviour.

**Comment by piotrowski** [comment]
It doesn't open it, it just does, whatever `FeedbackManager.register()` does.

**Comment by mikeljames** [comment]
Oh right, but does it actually have any side effects? Does it cause any
memory issues?

**Comment by piotrowski** [comment]
Sorry, don't know - that's actually why I opened this ticket. You could ask the HockeyApp guys in their support forum or via email and post the answer here, then we know if this is actually a problem that has to be fixed ;)

**Comment by mikeljames** [comment]
Yeah might do that. :)

**Comment by lostintangent** [comment]
If you take a look at the implementation of [`FeedbackManager.register`](https://github.com/bitstadium/HockeySDK-Android/blob/develop/hockeysdk/src/main/java/net/hockeyapp/android/FeedbackManager.java#L171), it is simply loading some app state, that wouldn't have any noticeable impact on perf or memory usage. The HockeyApp team doesn't have any concerns with this method being called all the time, so I'm going to close this issue for now. 

If anyone finds any runtime concerns with this, please re-open it and we can definitely consider adding a parameter to `start` that allows controlling whether or not `FeedbackManager.register` is called.
